export const EDIT_USER = "EDIT_USER";
export const USER_FILTER = "USER_FILTER";
export const ON_LIST_USER="ON_LIST_USER"

export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const ON_LIST_CATEGORY="ON_LIST_CATEGORY"